name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Permissão de diretório
        run: git config --global --add safe.directory C:/emals-app

      - name: Atualizar código
        working-directory: C:\emals-app
        run: git pull origin main

      - name: Reiniciar backend
        run: |
          (Get-WmiObject Win32_Service -Filter "Name='EmaisBackend'").StopService()
          Start-Sleep -Seconds 3
          (Get-WmiObject Win32_Service -Filter "Name='EmaisBackend'").StartService()
        shell: powershell
