name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Permissão de diretório
        run: git config --global --add safe.directory C:/emals-app

      - name: Atualizar código
        working-directory: C:\emals-app
        run: git pull origin main

      - name: Reiniciar backend
        working-directory: C:\emals-service
        run: .\emals-backend.exe restart
